// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL621k9QSuytNcNbvpEOiXbRF9ApfyAQU',
    appId: '1:201503646001:android:3c222fa321e468e5d65010',
    messagingSenderId: '201503646001',
    projectId: 'chatup-6a40e',
    databaseURL: 'https://chatup-6a40e-default-rtdb.firebaseio.com',
    storageBucket: 'chatup-6a40e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDphTWcwpvTxe6YMM0SFQOFvsLbCQL07As',
    appId: '1:201503646001:ios:eb45a00ea55932ead65010',
    messagingSenderId: '201503646001',
    projectId: 'chatup-6a40e',
    databaseURL: 'https://chatup-6a40e-default-rtdb.firebaseio.com',
    storageBucket: 'chatup-6a40e.appspot.com',
    androidClientId: '201503646001-6u7frk00dbkavu4kaa1f3v1pbkmfaajj.apps.googleusercontent.com',
    iosClientId: '201503646001-kc9glqbn1medhevm1id21ibjcfstvu70.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatUp',
  );
}
